name: Check Version Pins
on:
    push:
        branches: [main]
    pull_request:

jobs:
    pin-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
            - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
            - name: Run pin checker
              run: python scripts/ci/check-pins.py
