name: Python Lint Suite
permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - stt
          - tts
          - discord_indexer
          - discord_attachment_indexer
          - discord_attachment_embedder

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"

      - name: Install Hy
        run: python -m pip install hy dotenv mypy

      - name: Cache pip dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('services/py/{0}/Pipfile.lock', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache npm dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: make system-deps setup-pipenv setup-python-service-${{ matrix.service }}

      - name: Install lint dependencies
        run: python -m pip install flake8

      - name: Lint
        run: make lint-python-service-${{ matrix.service }}

      - name: Typecheck
        run: make typecheck-python
