# .github/workflows/on-pr-to-staging.yml
name: on-pr-to-staging
on: { pull_request: { branches: ["dev/staging"] } }
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: pnpm }
      - run: corepack enable && pnpm i --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Optional: spin up Nx Cloud agents to parallelize
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - run: pnpm nx affected -t lint test build
